---
version: '3'
services:
  service:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./api:/opt/climate-search/api
      - ./data:/opt/climate-search/data
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    entrypoint: [
      "nohup",
      "poetry",
      "run",
      "uvicorn",
      "api.server:app",
      "--reload",
      "--host",
      "0.0.0.0"
    ]
  rq-worker:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    volumes:
      - ./api:/opt/climate-search/api
    env_file:
      - .env
    depends_on:
      - redis
    entrypoint: [
      "poetry",
      "run", 
      "rq", 
      "worker-pool",
      "subset",
      "preview",
      "-n5",
      "-u",
      "redis://redis-climate-data:6379" 
    ]
  jupyter:
    build:
      context: ./
      dockerfile: ./docker/jupyter/Dockerfile
    volumes:
      - ./api:/opt/climate-search/api
      - ./data:/opt/climate-search/data
    ports:
      - "8888:8888"
    env_file:
      - .env
  # minio:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/minio/Dockerfile
  #   volumes:
  #     - ./data:/data
  #   ports:
  #     - "9090:9000"
  #     - "9091:9001"
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER:-miniouser}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-miniopass}
  redis:
    container_name: redis-climate-data
    image: redis
