version: '3'
services:
  service:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./api:/opt/climate-search/api
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_ORG_ID=${OPENAI_ORG_ID}